Added initial documentation files
PxTools/Px.Utils pull request #1
Opened 2024-01-24 08:27 UTC by jsaarimaa

Added initial documentation files README.md and CONTRIBUTING.md. More content will be added to these files when more features are impelemted.

2024-01-26 07:35 UTC, sakari-malkki approved these changes

2024-01-27 08:20 UTC, LauraRocks commented on docs/README.md
> +We do not want to limit the user if not abolutely necessary. There are variations in the metadata between users and we want to support as many as possible.
Typo abolutely

2024-01-27 08:21 UTC, LauraRocks requested changes
Fix typo as indicated in the comment

2024-01-29 06:37 UTC, jsaarimaa commented on docs/README.md
> +We do not want to limit the user if not abolutely necessary. There are variations in the metadata between users and we want to support as many as possible.
Fixed

2024-01-29 12:31 UTC, sakari-malkki approved these changes
Typo fixed, looks good

2024-01-29 13:37 UTC, LauraRocks approved these changes

2024-01-30 06:32 UTC, merged